version: '3.2'
services:
  webserver:
    build: ./php-73-apache-xdebug-28
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    environment:
      #change the line below with your IP address
      XDEBUG_CONFIG: remote_host=192.168.2.108
  mysql:
      build: ./mysql
      ports:
        - "33306:3306"
      volumes:
        - ./data:/var/lib/mysql
